// ╔══════════════════════════════════════════════════╗
// ║  Compiled by RexScript v0.1.0 · Hatchling        ║
// ║  "Agents don't browse. They hunt."             ║
// ╚══════════════════════════════════════════════════╝
//
// Do not edit this file. Edit the source .rex file.
import __rex from '@rexscript/runtime';
import __xrisk from '@rexscript/xrisk';
import __rosetta from '@rexscript/rosetta';

async function __rex_main() {
  await __xrisk.goalStart("\"Find best deals\"", budget < 100, {"line":1,"column":1});
  try {
    await __xrisk.rationale("\"Start fresh scope to avoid memory bloat\"", {"line":2,"column":3});
    ;
    await __rex.workspaceStart("\"deals\"");
    try {
      try {
        let __rex_attempt_2 = 0;
        while (__rex_attempt_2 < 3) {
          __rex_attempt_2++;
          try {
            await __xrisk.before({ action: "observe", target: "https://example.com/deals", capability: "NETWORK", loc: {"line":5,"column":7} });
            const __rex_result_1 = await __rex.observe("https://example.com/deals", { session: null });
            await __xrisk.after({ action: "observe", riskLevel: "LOW", result: __rex_result_1 ?? null, loc: {"line":5,"column":7} });
            const $dealsPage = __rex_result_1;
            ;
            const $data = __rex.pipe($dealsPage, extract_deals);
            let $isGood = false;
            if (confidence ( $data ) > 80) {
              $isGood = true;
            } else {
              $isGood = false;
              throw "Not enough confidence";
            }
            break;
          } catch (err) {
            if (__rex.isFailure(err, "Timeout")) {
              __xrisk.emit({ "error" : "timed out" });
              ;
            }
            else if (true) {
              __xrisk.emit({ "error" : "unknown failure" });
              ;
            }
            else {
              throw err;
            }
          }
        }
      } finally {
        await __xrisk.rationale("\"Cleanup phase\"", {"line":20,"column":7});
        ;
      }
    } finally {
      await __rex.workspaceEnd();
    }
  } finally {
    await __xrisk.goalEnd();
  }
}

await __rex_main();
