// ╔══════════════════════════════════════════════════╗
// ║  Compiled by RexScript v0.1.0 · Hatchling        ║
// ║  "Agents don't browse. They hunt."             ║
// ╚══════════════════════════════════════════════════╝
//
// Do not edit this file. Edit the source .rex file.
import __rex from '@rexscript/runtime';
import __xrisk from '@rexscript/xrisk';
import __rosetta from '@rexscript/rosetta';

async function __rex_main() {
  __rex.registerTool("fetch_docs", async ($topic) => {
      await __xrisk.rationale("\"Fetching documents from internal knowledge base\"", {"line":2,"column":3});
      await __xrisk.before({ action: "use.instead", target: "python", capability: "FOREIGN_EXEC", loc: {"line":3,"column":3} });
      const __rex_result_1 = await __rex.useInstead({ hint: "python", content: "# mock fetch return [ { \"title\" : \"Agent Patterns\" , \"content\" : \"Agents hunt.\" } ]" });
      await __xrisk.after({ action: "use.instead", riskLevel: "MEDIUM", result: __rex_result_1 ?? null, loc: {"line":3,"column":3} });
      const $docs = __rex_result_1;
      return $docs;
  });
  await __xrisk.goalStart("\"Analyze document type\"", null, {"line":10,"column":1});
  try {
    await __rex.equip("fetch_docs");
    const $query = "AI";
    const $data = __rex.pipe($query, fetch_docs);
    await __xrisk.before({ action: "remember", target: $data, capability: "MEMORY", loc: {"line":16,"column":3} });
    const __rex_result_2 = await __rex.remember($data, ["docs"], { mode: "vector" });
    await __xrisk.after({ action: "remember", riskLevel: "LOW", result: __rex_result_2 ?? null, loc: {"line":16,"column":3} });
    ;
    await __xrisk.before({ action: "recall", target: ["docs"], capability: "MEMORY", loc: {"line":18,"column":3} });
    const __rex_result_3 = await __rex.recall(["docs"], { threshold: 80, mode: "vector" });
    await __xrisk.after({ action: "recall", riskLevel: "LOW", result: __rex_result_3 ?? null, loc: {"line":18,"column":3} });
    const $similarDocs = __rex_result_3;
    ;
    const __rex_assess_4 = await __rex.assess($similarDocs, ["\"contains patterns\"","\"contains nonsense\""]);
    if (__rex_assess_4 === "\"contains patterns\"") {
      __rex.flag($similarDocs, "useful");
      ;
    }
    else if (__rex_assess_4 === "\"contains nonsense\"") {
      return;
      ;
    }
    else {
      throw "Unknown doc type";
    }
  } finally {
    await __xrisk.goalEnd();
  }
}

await __rex_main();
