// ╔══════════════════════════════════════════════════╗
// ║  Compiled by RexScript v0.1.0 · Hatchling        ║
// ║  "Agents don't browse. They hunt."             ║
// ╚══════════════════════════════════════════════════╝
//
// Do not edit this file. Edit the source .rex file.
import __rex from '@rexscript/runtime';
import __xrisk from '@rexscript/xrisk';
import __rosetta from '@rexscript/rosetta';

async function __rex_main() {
  const $datadogKey = "12345";
  await __xrisk.configureTelemetry({ exporter: "\"datadog\"", endpoint: "\"https://http-intake.logs.datadoghq.com/api/v2/logs\"", key: $datadogKey });
  await __xrisk.goalStart("\"Scrape e-commerce listings\"", {"budget":0.05,"timeoutMs":30000}, {"line":9,"column":1});
  try {
    await __xrisk.rationale("\"Beginning scrape with strict $0.05 budget\"", {"line":13,"column":3});
    try {
      await __xrisk.before({ action: "hunt", target: "https://example.com/products", capability: "NETWORK", loc: {"line":16,"column":5} });
      const __rex_result_1 = await __rex.hunt("https://example.com/products", { session: null });
      await __xrisk.after({ action: "hunt", riskLevel: "LOW", result: __rex_result_1 ?? null, loc: {"line":16,"column":5} });
      const $products = __rex_result_1;
      ;
      await __xrisk.before({ action: "synthesise", target: null, capability: "MODEL", loc: {"line":17,"column":5} });
      const __rex_result_2 = await __rex.synthesise([$products]);
      await __xrisk.after({ action: "synthesise", riskLevel: "MEDIUM", result: __rex_result_2 ?? null, loc: {"line":17,"column":5} });
      const $clean = __rex_result_2;
      ;
    } catch (err) {
      if (__rex.isFailure(err, "Timeout")) {
        __xrisk.emit({ "error" : "timed out" });
        ;
      }
      else {
        throw err;
      }
    }
  } finally {
    await __xrisk.goalEnd();
  }
}

await __rex_main();
