// ╔══════════════════════════════════════════════════╗
// ║  Compiled by RexScript v0.1.0 · Hatchling        ║
// ║  "Agents don't browse. They hunt."             ║
// ╚══════════════════════════════════════════════════╝
//
// Do not edit this file. Edit the source .rex file.
import __rex from '@rexscript/runtime';
import __xrisk from '@rexscript/xrisk';
import __rosetta from '@rexscript/rosetta';

async function __rex_main() {
  const $budget = { "budget" : 0.10 };
  const $workerBot = await __rex.spawn("\"DetailScraper\"", $budget);
  let $p1, $p2;
  const __rex_parallel_3 = await __rex.parallel([
    async () => {
      await __xrisk.before({ action: "hunt", target: "https://example.com/item/1", capability: "NETWORK", loc: {"line":6,"column":5} });
      const __rex_result_1 = await __rex.hunt("https://example.com/item/1", { session: null });
      await __xrisk.after({ action: "hunt", riskLevel: "LOW", result: __rex_result_1 ?? null, loc: {"line":6,"column":5} });
      const $p1 = __rex_result_1;
      return { name: "$p1", value: $p1 };
    },
    async () => {
      ;
      return null;
    },
    async () => {
      await __xrisk.before({ action: "hunt", target: "https://example.com/item/2", capability: "NETWORK", loc: {"line":7,"column":5} });
      const __rex_result_2 = await __rex.hunt("https://example.com/item/2", { session: null });
      await __xrisk.after({ action: "hunt", riskLevel: "LOW", result: __rex_result_2 ?? null, loc: {"line":7,"column":5} });
      const $p2 = __rex_result_2;
      return { name: "$p2", value: $p2 };
    },
    async () => {
      ;
      return null;
    }
  ], { limit: 5, distributed: true });
  for (const __r of (__rex_parallel_3.results || [])) {
    if (!__r || !__r.name) continue;
    switch (__r.name) {
      case "$p1": $p1 = __r.value; break;
      case "$p2": $p2 = __r.value; break;
      default: break;
    }
  }
  await __xrisk.before({ action: "synthesise", target: null, capability: "MODEL", loc: {"line":8,"column":8} });
  const __rex_result_4 = await __rex.synthesise([$p1, $p2]);
  await __xrisk.after({ action: "synthesise", riskLevel: "MEDIUM", result: __rex_result_4 ?? null, loc: {"line":8,"column":8} });
  const $merged = __rex_result_4;
  ;
  await __rex.send({ "urls" : $merged }, $workerBot);
  try {
    const $results = await __rex.receive($workerBot);
    await __xrisk.before({ action: "remember", target: $results, capability: "MEMORY", loc: {"line":14,"column":5} });
    const __rex_result_5 = await __rex.remember($results, ["output"], { mode: "vector" });
    await __xrisk.after({ action: "remember", riskLevel: "LOW", result: __rex_result_5 ?? null, loc: {"line":14,"column":5} });
    ;
  } catch (err) {
    if (__rex.isFailure(err, "Timeout")) {
      await __xrisk.configureTelemetry({ exporter: "\"datadog\"", endpoint: "\"http-intake\"", key: $budget });
    }
    else {
      throw err;
    }
  }
}

await __rex_main();
