// ╔══════════════════════════════════════════════════╗
// ║  Compiled by RexScript v0.1.0 · Hatchling        ║
// ║  "Agents don't browse. They hunt."             ║
// ╚══════════════════════════════════════════════════╝
//
// Do not edit this file. Edit the source .rex file.
import __rex from '@rexscript/runtime';
import __xrisk from '@rexscript/xrisk';
import __rosetta from '@rexscript/rosetta';

async function __rex_main() {
  await __xrisk.configureSecurity({ sandbox: "\"docker\"", lockdown: "strict" });
  const $key = vault ( "MY_API_KEY" );
  await __xrisk.before({ action: "use.instead", target: "python", capability: "FOREIGN_EXEC", loc: {"line":8,"column":1} });
  const __rex_result_1 = await __rex.useInstead({ hint: "python", content: "import os print ( \"running isolated\" )" });
  await __xrisk.after({ action: "use.instead", riskLevel: "MEDIUM", result: __rex_result_1 ?? null, loc: {"line":8,"column":1} });
  const $data = __rex_result_1;
  await __xrisk.before({ action: "observe", target: "https://example.com", capability: "NETWORK", loc: {"line":13,"column":1} });
  const __rex_result_2 = await __rex.observe("https://example.com", { session: null });
  await __xrisk.after({ action: "observe", riskLevel: "LOW", result: __rex_result_2 ?? null, loc: {"line":13,"column":1} });
  const $content = __rex_result_2;
  ;
  try {
    await __xrisk.before({ action: "synthesise", target: null, capability: "MODEL", loc: {"line":16,"column":5} });
    const __rex_result_3 = await __rex.synthesise([$content]);
    await __xrisk.after({ action: "synthesise", riskLevel: "MEDIUM", result: __rex_result_3 ?? null, loc: {"line":16,"column":5} });
    const $understanding = __rex_result_3;
    ;
  } catch (err) {
    if (__rex.isFailure(err, "Timeout")) {

    }
    else {
      throw err;
    }
  }
}

await __rex_main();
