// ╔══════════════════════════════════════════════════╗
// ║  Compiled by RexScript v0.1.0 · Hatchling        ║
// ║  "Agents don't browse. They hunt."             ║
// ╚══════════════════════════════════════════════════╝
//
// Do not edit this file. Edit the source .rex file.
import __rex from '@rexscript/runtime';
import __xrisk from '@rexscript/xrisk';
import __rosetta from '@rexscript/rosetta';

async function __rex_main() {
  const base = "https://example.com";
  const route = "/news";
  const url = base + route;
  try {
    await __xrisk.before({ action: "observe", target: url, capability: "NETWORK", loc: {"line":6,"column":3} });
    const __rex_result_1 = await __rex.observe(url, { session: null });
    await __xrisk.after({ action: "observe", riskLevel: "LOW", result: __rex_result_1 ?? null, loc: {"line":6,"column":3} });
    const $page = __rex_result_1;
    await __xrisk.before({ action: "find", target: "headline", capability: "READ", loc: {"line":7,"column":3} });
    const __rex_result_2 = await __rex.find("headline", $page);
    await __xrisk.after({ action: "find", riskLevel: "LOW", result: __rex_result_2 ?? null, loc: {"line":7,"column":3} });
    const $headline = __rex_result_2;
  } catch (err) {
    if (true) {
      return;
    }
    else {
      throw err;
    }
  }
}

await __rex_main();
