// ╔══════════════════════════════════════════════════╗
// ║  Compiled by RexScript v0.1.0 · Hatchling        ║
// ║  "Agents don't browse. They hunt."             ║
// ╚══════════════════════════════════════════════════╝
//
// Do not edit this file. Edit the source .rex file.
import __rex from '@rexscript/runtime';
import __xrisk from '@rexscript/xrisk';
import __rosetta from '@rexscript/rosetta';

async function __rex_main() {
  try {
    await __xrisk.before({ action: "observe", target: "https://example.com", capability: "NETWORK", loc: {"line":2,"column":3} });
    const __rex_result_1 = await __rex.observe("https://example.com", { session: null });
    await __xrisk.after({ action: "observe", riskLevel: "LOW", result: __rex_result_1 ?? null, loc: {"line":2,"column":3} });
    const $page = __rex_result_1;
  } catch (err) {
    if (__rex.isFailure(err, "BlockedByBot")) {
      await __rex.rotateProxy();
      return __rex.retry();
    }
    else if (__rex.isFailure(err, "QueryFailed")) {

      return [ ];
    }
    else if (true) {
      return;
    }
    else {
      throw err;
    }
  }
}

await __rex_main();
